"""empty message

Revision ID: 00e9d73a547b
Revises: 66c98860e322
Create Date: 2016-06-26 22:13:46.359230

"""

# revision identifiers, used by Alembic.
revision = '00e9d73a547b'
down_revision = '66c98860e322'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_refreshed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_refreshed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'image', sa.Column('live_data', sa.Boolean(), nullable=True))
    op.add_column(u'item', sa.Column('live_data', sa.Boolean(), nullable=True))
    op.add_column(u'offer', sa.Column('live_data', sa.Boolean(), nullable=True))
    op.add_column(u'parent_item', sa.Column('live_data', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'parent_item', 'live_data')
    op.drop_column(u'offer', 'live_data')
    op.drop_column(u'item', 'live_data')
    op.drop_column(u'image', 'live_data')
    op.drop_table('last_refreshed')
    ### end Alembic commands ###
