"""empty message

Revision ID: 11fa892498fa
Revises: 297c7feec4c1
Create Date: 2016-04-26 21:53:31.211922

"""

# revision identifiers, used by Alembic.
revision = '11fa892498fa'
down_revision = '297c7feec4c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variation')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_ASIN', sa.VARCHAR(length=40), nullable=True),
    sa.Column('ASIN', sa.VARCHAR(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
