"""empty message

Revision ID: 3b1996d98e3d
Revises: 11e6f135b31c
Create Date: 2016-03-28 17:19:19.913919

"""

# revision identifiers, used by Alembic.
revision = '3b1996d98e3d'
down_revision = '11e6f135b31c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('availability', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'availability')
    ### end Alembic commands ###
