"""empty message

Revision ID: 47d8191852c2
Revises: 11fa892498fa
Create Date: 2016-04-27 22:34:10.394256

"""

# revision identifiers, used by Alembic.
revision = '47d8191852c2'
down_revision = '11fa892498fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_on_wishlist', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'is_on_wishlist')
    ### end Alembic commands ###
