"""empty message

Revision ID: ac660895811f
Revises: 47d8191852c2
Create Date: 2016-04-28 12:38:20.224140

"""

# revision identifiers, used by Alembic.
revision = 'ac660895811f'
down_revision = '47d8191852c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('offer_source', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'offer_source')
    ### end Alembic commands ###
